# Generated by Django 5.0.6 on 2024-06-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
